// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SatteliteManagment;

namespace SatteliteManagment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901112123_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SatteliteManagment.Entities.FileTransferPacketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea");

                    b.Property<int>("DescriptionId")
                        .HasColumnType("integer");

                    b.Property<byte>("FileId")
                        .HasColumnType("smallint");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<byte>("Result")
                        .HasColumnType("smallint");

                    b.Property<byte>("Size")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId")
                        .IsUnique();

                    b.ToTable("FileTransferPackets");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.LeafEntities.CoilMagnetMomentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DescriptionId")
                        .HasColumnType("integer");

                    b.Property<int>("MagnetMoment")
                        .HasColumnType("integer");

                    b.Property<byte>("Result")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId")
                        .IsUnique();

                    b.ToTable("CoilMagnetMoments");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.LeafEntities.FileRequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea");

                    b.Property<int>("DescriptionId")
                        .HasColumnType("integer");

                    b.Property<byte>("FileId")
                        .HasColumnType("smallint");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<byte>("Result")
                        .HasColumnType("smallint");

                    b.Property<byte>("Size")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId")
                        .IsUnique();

                    b.ToTable("FileRequests");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.LeafEntities.ModuleStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DescriptionId")
                        .HasColumnType("integer");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("ModuleStatus")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId")
                        .IsUnique();

                    b.ToTable("ModuleStatuses");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.LeafEntities.MotorSpeedEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DescriptionId")
                        .HasColumnType("integer");

                    b.Property<byte>("Result")
                        .HasColumnType("smallint");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId")
                        .IsUnique();

                    b.ToTable("MotorSpeeds");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.LeafEntities.ReprogrammingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DescriptionId")
                        .HasColumnType("integer");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<byte>("Result")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId")
                        .IsUnique();

                    b.ToTable("Reprogrammings");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.LeafEntities.TimeSetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DescriptionId")
                        .HasColumnType("integer");

                    b.Property<byte>("Result")
                        .HasColumnType("smallint");

                    b.Property<long>("TimeSet")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId")
                        .IsUnique();

                    b.ToTable("TimeSets");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.LeafEntities.VerifyCheckSumEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("Crc")
                        .HasColumnType("bigint");

                    b.Property<int>("DescriptionId")
                        .HasColumnType("integer");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<byte>("Result")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId")
                        .IsUnique();

                    b.ToTable("VerifyCheckSums");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.PacketDescriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte>("packetType")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("PacketDescriptions");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.PacketInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("ACK_REQ")
                        .HasColumnType("boolean");

                    b.Property<bool>("ACK_TYP")
                        .HasColumnType("boolean");

                    b.Property<byte>("AES_CRC")
                        .HasColumnType("smallint");

                    b.Property<bool>("BROADCAST")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DestAddr")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("SourceAddr")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("packetID")
                        .HasColumnType("bigint");

                    b.Property<byte>("payload_lth")
                        .HasColumnType("smallint");

                    b.Property<byte>("retrCount")
                        .HasColumnType("smallint");

                    b.Property<short>("rssi")
                        .HasColumnType("smallint");

                    b.Property<short>("snr")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("PacketInfos");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.RadioPacketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DescriptionId")
                        .HasColumnType("integer");

                    b.Property<int>("PacketInfoId")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .HasColumnType("text");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId")
                        .IsUnique();

                    b.HasIndex("PacketInfoId")
                        .IsUnique();

                    b.ToTable("RadioPackets");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.StoredFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("Address")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StoredFiles");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.TlmPacketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("AngularRate")
                        .HasColumnType("real");

                    b.Property<float>("BatChargePower")
                        .HasColumnType("real");

                    b.Property<float>("BatDischargePower")
                        .HasColumnType("real");

                    b.Property<float>("BatteryV")
                        .HasColumnType("real");

                    b.Property<int>("DescriptionId")
                        .HasColumnType("integer");

                    b.Property<float>("MagFieldAbs")
                        .HasColumnType("real");

                    b.Property<float>("PvPower1")
                        .HasColumnType("real");

                    b.Property<float>("PvPower2")
                        .HasColumnType("real");

                    b.Property<float>("PvPower3")
                        .HasColumnType("real");

                    b.Property<byte>("ResetCounter")
                        .HasColumnType("smallint");

                    b.Property<long>("StatusFlags")
                        .HasColumnType("bigint");

                    b.Property<float>("Temperature1")
                        .HasColumnType("real");

                    b.Property<float>("Temperature2")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DescriptionId")
                        .IsUnique();

                    b.ToTable("TlmPackets");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.FileTransferPacketEntity", b =>
                {
                    b.HasOne("SatteliteManagment.Entities.PacketDescriptionEntity", "DescriptionEntity")
                        .WithOne()
                        .HasForeignKey("SatteliteManagment.Entities.FileTransferPacketEntity", "DescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SatteliteManagment.Entities.LeafEntities.CoilMagnetMomentEntity", b =>
                {
                    b.HasOne("SatteliteManagment.Entities.PacketDescriptionEntity", "DescriptionEntity")
                        .WithOne()
                        .HasForeignKey("SatteliteManagment.Entities.LeafEntities.CoilMagnetMomentEntity", "DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SatteliteManagment.Entities.LeafEntities.FileRequestEntity", b =>
                {
                    b.HasOne("SatteliteManagment.Entities.PacketDescriptionEntity", "DescriptionEntity")
                        .WithOne()
                        .HasForeignKey("SatteliteManagment.Entities.LeafEntities.FileRequestEntity", "DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SatteliteManagment.Entities.LeafEntities.ModuleStatusEntity", b =>
                {
                    b.HasOne("SatteliteManagment.Entities.PacketDescriptionEntity", "DescriptionEntity")
                        .WithOne()
                        .HasForeignKey("SatteliteManagment.Entities.LeafEntities.ModuleStatusEntity", "DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SatteliteManagment.Entities.LeafEntities.MotorSpeedEntity", b =>
                {
                    b.HasOne("SatteliteManagment.Entities.PacketDescriptionEntity", "DescriptionEntity")
                        .WithOne()
                        .HasForeignKey("SatteliteManagment.Entities.LeafEntities.MotorSpeedEntity", "DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SatteliteManagment.Entities.LeafEntities.ReprogrammingEntity", b =>
                {
                    b.HasOne("SatteliteManagment.Entities.PacketDescriptionEntity", "DescriptionEntity")
                        .WithOne()
                        .HasForeignKey("SatteliteManagment.Entities.LeafEntities.ReprogrammingEntity", "DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SatteliteManagment.Entities.LeafEntities.TimeSetEntity", b =>
                {
                    b.HasOne("SatteliteManagment.Entities.PacketDescriptionEntity", "DescriptionEntity")
                        .WithOne()
                        .HasForeignKey("SatteliteManagment.Entities.LeafEntities.TimeSetEntity", "DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SatteliteManagment.Entities.LeafEntities.VerifyCheckSumEntity", b =>
                {
                    b.HasOne("SatteliteManagment.Entities.PacketDescriptionEntity", "DescriptionEntity")
                        .WithOne()
                        .HasForeignKey("SatteliteManagment.Entities.LeafEntities.VerifyCheckSumEntity", "DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SatteliteManagment.Entities.RadioPacketEntity", b =>
                {
                    b.HasOne("SatteliteManagment.Entities.PacketDescriptionEntity", "PacketDescription")
                        .WithOne()
                        .HasForeignKey("SatteliteManagment.Entities.RadioPacketEntity", "DescriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SatteliteManagment.Entities.PacketInfoEntity", "PacketInfo")
                        .WithOne("RadioPacketEntity")
                        .HasForeignKey("SatteliteManagment.Entities.RadioPacketEntity", "PacketInfoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SatteliteManagment.Entities.TlmPacketEntity", b =>
                {
                    b.HasOne("SatteliteManagment.Entities.PacketDescriptionEntity", "DescriptionEntity")
                        .WithOne()
                        .HasForeignKey("SatteliteManagment.Entities.TlmPacketEntity", "DescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
