// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SatteliteManagment;

namespace SatteliteManagment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812073129_AddStoredFileEntity")]
    partial class AddStoredFileEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SatteliteManagment.Entities.FileTransferPacketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea");

                    b.Property<byte>("FileId")
                        .HasColumnType("smallint");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int>("PacketInfoId")
                        .HasColumnType("integer");

                    b.Property<byte>("Size")
                        .HasColumnType("smallint");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("PacketInfoId")
                        .IsUnique();

                    b.ToTable("FileTransferPackets");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.PacketInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("ACK_REQ")
                        .HasColumnType("boolean");

                    b.Property<bool>("ACK_TYP")
                        .HasColumnType("boolean");

                    b.Property<byte>("AES_CRC")
                        .HasColumnType("smallint");

                    b.Property<bool>("BROADCAST")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DestAddr")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("SourceAddr")
                        .HasColumnType("numeric(20,0)");

                    b.Property<long>("packetID")
                        .HasColumnType("bigint");

                    b.Property<byte>("payload_lth")
                        .HasColumnType("smallint");

                    b.Property<byte>("retrCount")
                        .HasColumnType("smallint");

                    b.Property<short>("rssi")
                        .HasColumnType("smallint");

                    b.Property<short>("snr")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("PacketInfos");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.StoredFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("Address")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StoredFiles");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.TlmPacketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("AngularRate")
                        .HasColumnType("real");

                    b.Property<float>("BatChargePower")
                        .HasColumnType("real");

                    b.Property<float>("BatDischargePower")
                        .HasColumnType("real");

                    b.Property<float>("BatteryV")
                        .HasColumnType("real");

                    b.Property<float>("MagFieldAbs")
                        .HasColumnType("real");

                    b.Property<int>("PacketInfoId")
                        .HasColumnType("integer");

                    b.Property<float>("PvPower1")
                        .HasColumnType("real");

                    b.Property<float>("PvPower2")
                        .HasColumnType("real");

                    b.Property<float>("PvPower3")
                        .HasColumnType("real");

                    b.Property<byte>("ResetCounter")
                        .HasColumnType("smallint");

                    b.Property<long>("StatusFlags")
                        .HasColumnType("bigint");

                    b.Property<float>("Temperature1")
                        .HasColumnType("real");

                    b.Property<float>("Temperature2")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PacketInfoId")
                        .IsUnique();

                    b.ToTable("TlmPackets");
                });

            modelBuilder.Entity("SatteliteManagment.Entities.FileTransferPacketEntity", b =>
                {
                    b.HasOne("SatteliteManagment.Entities.PacketInfoEntity", "PacketInfo")
                        .WithOne("FileTransferPacket")
                        .HasForeignKey("SatteliteManagment.Entities.FileTransferPacketEntity", "PacketInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SatteliteManagment.Entities.TlmPacketEntity", b =>
                {
                    b.HasOne("SatteliteManagment.Entities.PacketInfoEntity", "PacketInfo")
                        .WithOne("TlmPacket")
                        .HasForeignKey("SatteliteManagment.Entities.TlmPacketEntity", "PacketInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
